"$schema" = 'https://starship.rs/config-schema.json'

# format = """
# $directory\
# $bun\
# $git_branch\
# $fill\
# $cmd_duration\
# $line_break\
# $character"""

format = """$directory$character"""

add_newline = false

[package]
disabled = true

