build-final-image: build-terminal-server build-coedit-image

build-terminal-server:
	@echo "-> RUN:terminal-server.mk"
	make -f terminal-server.mk

build-coedit-image:
	@echo "-> RUN:final-image.mk"
	make -f coedit.mk

