import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'

import { Provider } from 'jotai'

import { QueryProvider } from '#/components/provider'
import { cn } from '#/utils/style'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'coedit',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body className={cn(inter.className, 'bg-gray-1 text-gray-12')}>
        <QueryProvider>
          <Provider>{children}</Provider>
        </QueryProvider>
      </body>
    </html>
  )
}
