"$schema" = "./node_modules/wrangler/config-schema.json"
name = "api-coedit"
main = "src/index.ts"

compatibility_date = "2026-08-07"
compatibility_flags = [ "nodejs_compat" ]

workers_dev = false

[dev]
port=5002

