name = "api-coedit"
compatibility_date = "2023-12-01"
compatibility_flags = [ "nodejs_compat" ]

[dev]
port=5000

[vars]
DB_URL="" # neon db

JWT_SECRET=""

RESEND_API_KEY=""
RESEND_FROM="team <abc@example.com>"

UPSTASH_REDIS_REST_TOKEN=""
UPSTASH_REDIS_REST_URL=""

RUNTIME="production" # production OR development

COOKIE_DOMAIN="localhost"
CORS_ORIGIN="http://localhost:5001"

CONTAINER_MODE='caddy' # mock OR caddy
