import fs from 'node:fs'
import path from 'node:path'

const root = path.join(import.meta.dir, '..')
const publicDir = path.join(root, 'public')
const themePath = path.join(root, 'src/utils/symbol-icon-theme.json')
const outPath = path.join(
  root,
  'src/app/(app)/ide/[id]/tree-file-icons.generated.ts'
)

type Theme = {
  iconDefinitions: Record<string, { iconPath: string }>
  fileExtensions: Record<string, string>
  fileNames: Record<string, string>
  file: string
}

const theme = JSON.parse(fs.readFileSync(themePath, 'utf8')) as Theme

function sanitizeId(key: string) {
  return `tree-icon-${key.replace(/[^a-zA-Z0-9_-]/g, '-')}`
}

function readIconSource(iconDefKey: string) {
  const def = theme.iconDefinitions[iconDefKey]
  if (!def) return null

  const relativePath = def.iconPath.replace(/^\.\//, '')
  const filePath = path.join(publicDir, relativePath)
  if (!fs.existsSync(filePath)) return null

  return fs.readFileSync(filePath, 'utf8')
}

function namespaceLocalIds(svgInner: string, symbolId: string) {
  const ids = [...svgInner.matchAll(/\bid="([^"]+)"/g)].map((m) => m[1])
  if (ids.length === 0) return svgInner

  let result = svgInner
  for (const id of [...new Set(ids)]) {
    const namespaced = `${symbolId}__${id}`
    result = result
      .split(`id="${id}"`)
      .join(`id="${namespaced}"`)
      .split(`url(#${id})`)
      .join(`url(#${namespaced})`)
      .split(`href="#${id}"`)
      .join(`href="${namespaced}"`)
  }
  return result
}

const INHERITABLE_ATTRS = new Set([
  'fill',
  'stroke',
  'stroke-width',
  'stroke-linecap',
  'stroke-linejoin',
  'stroke-miterlimit',
  'stroke-dasharray',
  'stroke-dashoffset',
  'fill-rule',
  'fill-opacity',
  'stroke-opacity',
  'color',
])

function extractInheritableAttrs(openingSvgTag: string) {
  const attrs: string[] = []
  for (const match of openingSvgTag.matchAll(/([\w:-]+)="([^"]*)"/g)) {
    const [, name, value] = match
    if (INHERITABLE_ATTRS.has(name)) attrs.push(`${name}="${value}"`)
  }
  return attrs.join(' ')
}

function buildSymbol(iconDefKey: string) {
  const source = readIconSource(iconDefKey)
  if (!source) return null

  const openingTagMatch = source.match(/^[\s\S]*?<svg[^>]*>/)
  const openingTag = openingTagMatch?.[0] ?? ''

  const viewBoxMatch = openingTag.match(/viewBox="([^"]+)"/)
  const viewBox = viewBoxMatch?.[1] ?? '0 0 24 24'
  const inheritedAttrs = extractInheritableAttrs(openingTag)

  const inner = source
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .trim()

  const symbolId = sanitizeId(iconDefKey)
  const namespacedInner = namespaceLocalIds(inner, symbolId)

  const symbolAttrs = [
    `id="${symbolId}"`,
    `viewBox="${viewBox}"`,
    inheritedAttrs,
  ]
    .filter(Boolean)
    .join(' ')

  return {
    id: symbolId,
    viewBox,
    markup: `  <symbol ${symbolAttrs}>\n    ${namespacedInner}\n  </symbol>`,
  }
}

const symbolsByIconDefKey = new Map<
  string,
  { id: string; viewBox: string; markup: string }
>()

function registerSymbol(iconDefKey: string) {
  if (symbolsByIconDefKey.has(iconDefKey)) return
  const symbol = buildSymbol(iconDefKey)
  if (symbol) symbolsByIconDefKey.set(iconDefKey, symbol)
}

for (const key of Object.values(theme.fileExtensions)) registerSymbol(key)
for (const key of Object.values(theme.fileNames)) registerSymbol(key)
registerSymbol(theme.file)

const byFileExtension: Record<string, { name: string; viewBox: string }> = {}
for (const [ext, iconDefKey] of Object.entries(theme.fileExtensions)) {
  const symbol = symbolsByIconDefKey.get(iconDefKey)
  if (symbol)
    byFileExtension[ext] = { name: symbol.id, viewBox: symbol.viewBox }
}

const byFileName: Record<string, { name: string; viewBox: string }> = {}
for (const [name, iconDefKey] of Object.entries(theme.fileNames)) {
  const symbol = symbolsByIconDefKey.get(iconDefKey)
  if (symbol) byFileName[name] = { name: symbol.id, viewBox: symbol.viewBox }
}

const defaultSymbol = symbolsByIconDefKey.get(theme.file)
if (!defaultSymbol) {
  throw new Error(
    `tree-icons: default file icon "${theme.file}" failed to resolve`
  )
}

const spriteSheet = `<svg data-icon-sprite aria-hidden="true" width="0" height="0">\n${[
  ...symbolsByIconDefKey.values(),
]
  .map((symbol) => symbol.markup)
  .join('\n')}\n</svg>`

const generated = `// AUTO-GENERATED by scripts/build-tree-icons.ts — do not edit by hand.
// Regenerate with \`bun run build:tree-icons\`.

export type TreeFileIconRemap = { name: string; viewBox: string }

export const TREE_FILE_ICON_SPRITE_SHEET = ${JSON.stringify(spriteSheet)}

export const TREE_FILE_ICON_BY_EXTENSION: Record<string, TreeFileIconRemap> =
  ${JSON.stringify(byFileExtension, null, 2)}

export const TREE_FILE_ICON_BY_FILE_NAME: Record<string, TreeFileIconRemap> =
  ${JSON.stringify(byFileName, null, 2)}

export const TREE_FILE_ICON_DEFAULT: TreeFileIconRemap = ${JSON.stringify({
  name: defaultSymbol.id,
  viewBox: defaultSymbol.viewBox,
})}
`

fs.writeFileSync(outPath, generated)

console.log(
  `built tree icon sprite (${symbolsByIconDefKey.size} icons, ${Object.keys(byFileExtension).length} extensions, ${Object.keys(byFileName).length} filenames) to ${path.relative(process.cwd(), outPath)}`
)
